name: Deploy to Namecheap Production Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to Server
      - name: Deploy to Namecheap server
        run: |
          ssh qaadxdgj@198.54.125.67 <<EOF
          cd /public_html
          chmod +x deploy.sh
          ./deploy.sh
          EOF
