- name: Deploy via SSH
  run: |
    ssh -p 21098 -tt -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
    SITE_ROOT=$(find /home/$SERVER_USER -name public_html -type d 2>/dev/null | head -n 1)
    if [ -z "$SITE_ROOT" ]; then
        echo "Could not find public_html directory"
        exit 1
    fi

    cd "$SITE_ROOT"

    if [ ! -d .git ]; then
        echo "Initializing git repository"
        git init
        git remote add origin $REPO_URL
        git fetch origin
        git checkout -b master origin/master
    else
        git pull origin master
    fi

    if [ -f composer.json ]; then
        if ! command -v composer &> /dev/null; then
            echo "Composer is not installed. Please install it on the server."
            exit 1
        fi
        composer install --no-interaction --prefer-dist --optimize-autoloader
    fi

    if [ -f artisan ]; then
        php artisan migrate --force
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear
        php artisan route:clear
        php artisan optimize
        chmod -R 775 storage bootstrap/cache
        chown -R $USER:www-data storage bootstrap/cache
    fi

    exit
    EOF
  env:
    REPO_URL: git@github.com:Sohail-Khan-dev/QaAdvanced.git
